go install github.com/golang/mock/mockgen@v1.6.0

find . -type f -name '*_mock.go' -exec rm {} \;
find . -type f -name '*.go-e' -exec rm {} \;

go mod tidy
go fmt ./...
go generate ./...
go fmt ./...
go test ./... -v

cd v2; go mod tidy
cd v2; go fmt ./...
cd v2; go generate ./...
cd v2; go fmt ./...
cd v2; go test ./... -v



