servers:
  testServer:
    host: localhost
    port: 9123

apis:
  delay_timeout_10:
    path: /delay
    server: testServer
    timeout: 10
    concurrency: 3
  delay_timeout_10_POST:
    path: /delay
    method: POST
    server: testServer
    timeout: 10
    concurrency: 3